/share/apps/python/3.9.5/bin/python3: can't open file '/share/nobackup/b5025250/FDTD_Models/TwoDimension/bin/../LoadedCapillaries/twoDsolve.py': [Errno 2] No such file or directory
/share/apps/python/3.9.5/bin/python3: can't open file '/share/nobackup/b5025250/FDTD_Models/TwoDimension/bin/../LoadedCapillaries/twoDsolve.py': [Errno 2] No such file or directory
/share/apps/python/3.9.5/bin/python3: can't open file '/share/nobackup/b5025250/FDTD_Models/TwoDimension/bin/../LoadedCapillaries/twoDsolve.py': [Errno 2] No such file or directory
/share/apps/python/3.9.5/bin/python3: can't open file '/share/nobackup/b5025250/FDTD_Models/TwoDimension/bin/../LoadedCapillaries/twoDsolve.py': [Errno 2] No such file or directory
/share/apps/python/3.9.5/bin/python3: can't open file '/share/nobackup/b5025250/FDTD_Models/TwoDimension/bin/../LoadedCapillaries/twoDsolve.py': [Errno 2] No such file or directory
/share/apps/python/3.9.5/bin/python3: can't open file '/share/nobackup/b5025250/FDTD_Models/TwoDimension/bin/../LoadedCapillaries/twoDsolve.py': [Errno 2] No such file or directory
/share/apps/python/3.9.5/bin/python3: can't open file '/share/nobackup/b5025250/FDTD_Models/TwoDimension/bin/../LoadedCapillaries/twoDsolve.py': [Errno 2] No such file or directory
/share/apps/python/3.9.5/bin/python3: can't open file '/share/nobackup/b5025250/FDTD_Models/TwoDimension/bin/../LoadedCapillaries/twoDsolve.py': [Errno 2] No such file or directory
/share/apps/python/3.9.5/bin/python3: can't open file '/share/nobackup/b5025250/FDTD_Models/TwoDimension/bin/../LoadedCapillaries/twoDsolve.py': [Errno 2] No such file or directory
/share/apps/python/3.9.5/bin/python3: can't open file '/share/nobackup/b5025250/FDTD_Models/TwoDimension/bin/../LoadedCapillaries/twoDsolve.py': [Errno 2] No such file or directory
/share/apps/python/3.9.5/bin/python3: can't open file '/share/nobackup/b5025250/FDTD_Models/TwoDimension/bin/../LoadedCapillaries/twoDsolve.py': [Errno 2] No such file or directory
/share/apps/python/3.9.5/bin/python3: can't open file '/share/nobackup/b5025250/FDTD_Models/TwoDimension/bin/../LoadedCapillaries/twoDsolve.py': [Errno 2] No such file or directory
/share/apps/python/3.9.5/bin/python3: can't open file '/share/nobackup/b5025250/FDTD_Models/TwoDimension/bin/../LoadedCapillaries/twoDsolve.py': [Errno 2] No such file or directory
/share/apps/python/3.9.5/bin/python3: can't open file '/share/nobackup/b5025250/FDTD_Models/TwoDimension/bin/../LoadedCapillaries/twoDsolve.py': [Errno 2] No such file or directory
/share/apps/python/3.9.5/bin/python3: can't open file '/share/nobackup/b5025250/FDTD_Models/TwoDimension/bin/../LoadedCapillaries/twoDsolve.py': [Errno 2] No such file or directory
/share/apps/python/3.9.5/bin/python3: can't open file '/share/nobackup/b5025250/FDTD_Models/TwoDimension/bin/../LoadedCapillaries/twoDsolve.py': [Errno 2] No such file or directory
/share/apps/python/3.9.5/bin/python3: can't open file '/share/nobackup/b5025250/FDTD_Models/TwoDimension/bin/../LoadedCapillaries/twoDsolve.py': [Errno 2] No such file or directory
/share/apps/python/3.9.5/bin/python3: can't open file '/share/nobackup/b5025250/FDTD_Models/TwoDimension/bin/../LoadedCapillaries/twoDsolve.py': [Errno 2] No such file or directory
srun: error: topsy-cn-1-3: tasks 0-17: Exited with exit code 2
